package handlers

import (
	"github.com/gin-gonic/gin"
	"net/http"
	"testing"

	"github.com/gujaratharva021-lgtm/ecommerce-backend/internal/database"
	"github.com/gujaratharva021-lgtm/ecommerce-backend/internal/models"
	"github.com/gujaratharva021-lgtm/ecommerce-backend/internal/services"
)

// ---------------------------------------------------------------------------
// BE-14: ConfirmDelivery must generate the invoice if missing (safety net)
// before posting the sales ledger entry, so a COD order never silently
// skips revenue recognition just because checkout-time invoice generation
// failed or was skipped.
// ---------------------------------------------------------------------------

func TestConfirmDelivery_GeneratesInvoiceIfMissingThenPostsLedger(t *testing.T) {
	r := newStatusGPSTestRouter()
	partner, order, token := acceptedOrderForStatusTest(t, r)
	otpCode := advanceToArrivedWithOTP(t, r, partner, order, token)

	// seedAssignOrder creates the order directly in the DB (bypassing
	// Checkout), so no invoice exists yet at this point - this is exactly
	// the "invoice generation was skipped" scenario BE-14 guards against.
	var preInvoice models.Invoice
	if err := database.DB.Where("order_id = ?", order.ID).First(&preInvoice).Error; err == nil {
		t.Fatalf("test setup invalid: invoice already exists before delivery confirmation")
	}

	setPartnerLocation(t, partner.ID, 23.0225, 72.5714)
	w := doRequest(r, http.MethodPut, deliveryStatusURL(order.ID), token, gin.H{"status": "delivered", "otp": otpCode})
	if w.Code != http.StatusOK {
		t.Fatalf("setup: marking delivered failed: %d %s", w.Code, w.Body.String())
	}

	// ConfirmDelivery requires a delivery proof photo - set it directly,
	// same as the real proof-upload endpoint would have.
	proofURL := "https://example.com/proof.jpg"
	if err := database.DB.Model(&models.Order{}).Where("id = ?", order.ID).
		Update("delivery_proof_url", proofURL).Error; err != nil {
		t.Fatalf("setup: failed to set delivery proof: %v", err)
	}

	w = doRequest(r, http.MethodPut, "/api/v1/delivery/orders/"+itoa(order.ID)+"/deliver", token, nil)
	if w.Code != http.StatusOK {
		t.Fatalf("expected 200 confirming delivery, got %d: %s", w.Code, w.Body.String())
	}

	var invoice models.Invoice
	if err := database.DB.Where("order_id = ?", order.ID).First(&invoice).Error; err != nil {
		t.Fatalf("expected invoice to be generated by ConfirmDelivery safety net, got error: %v", err)
	}

	var ledgerEntries []models.LedgerEntry
	if err := database.DB.Where("reference_type = ? AND reference_id = ?", "sale", order.ID).Find(&ledgerEntries).Error; err != nil {
		t.Fatalf("failed to query ledger entries: %v", err)
	}
	if len(ledgerEntries) == 0 {
		t.Errorf("expected sales ledger entries to be posted for order %d, found none", order.ID)
	}

	var fresh models.Order
	database.DB.First(&fresh, order.ID)
	if fresh.Status != models.OrderStatusDelivered {
		t.Errorf("expected order status 'delivered', got %v", fresh.Status)
	}
	if fresh.PaymentStatus != models.OrderPaymentStatusPaid {
		t.Errorf("expected COD order payment_status 'paid' after delivery, got %v", fresh.PaymentStatus)
	}
}

// TestConfirmDelivery_LedgerPostingIsIdempotent confirms a second delivery
// confirmation attempt (which is already blocked by the "already delivered"
// check) does not matter - PostSalesLedgerEntry itself is idempotent, so
// check) does not matter - PostSalesLedgerEntry itself is idempotent, so
// even if ConfirmDelivery were somehow called twice for the same order, no
// duplicate ledger entries would be created.
func TestConfirmDelivery_LedgerPostingIsIdempotent(t *testing.T) {
	r := newStatusGPSTestRouter()
	partner, order, token := acceptedOrderForStatusTest(t, r)
	otpCode := advanceToArrivedWithOTP(t, r, partner, order, token)

	setPartnerLocation(t, partner.ID, 23.0225, 72.5714)
	if w := doRequest(r, http.MethodPut, deliveryStatusURL(order.ID), token, gin.H{"status": "delivered", "otp": otpCode}); w.Code != http.StatusOK {
		t.Fatalf("setup: marking delivered failed: %d %s", w.Code, w.Body.String())
	}
	database.DB.Model(&models.Order{}).Where("id = ?", order.ID).Update("delivery_proof_url", "https://example.com/proof.jpg")

	w := doRequest(r, http.MethodPut, "/api/v1/delivery/orders/"+itoa(order.ID)+"/deliver", token, nil)
	if w.Code != http.StatusOK {
		t.Fatalf("expected 200 on first confirm, got %d: %s", w.Code, w.Body.String())
	}

	var afterFirstConfirm []models.LedgerEntry
	database.DB.Where("reference_type = ? AND reference_id = ?", "sale", order.ID).Find(&afterFirstConfirm)
	if len(afterFirstConfirm) == 0 {
		t.Fatalf("expected sales ledger entries after first confirm, found none")
	}

	// Simulate a duplicate ledger-post call directly (ConfirmDelivery itself
	// already blocks a second HTTP call via the 'already delivered' status
	// check, so this exercises PostSalesLedgerEntry's own idempotency guard
	// the way a retried background job or a race would).
	if err := services.PostSalesLedgerEntry(order.ID); err != nil {
		t.Fatalf("unexpected error on duplicate ledger post: %v", err)
	}

	var afterDuplicateCall []models.LedgerEntry
	database.DB.Where("reference_type = ? AND reference_id = ?", "sale", order.ID).Find(&afterDuplicateCall)
	if len(afterDuplicateCall) != len(afterFirstConfirm) {
		t.Errorf("expected ledger entry count unchanged after duplicate post (idempotent), before=%d after=%d", len(afterFirstConfirm), len(afterDuplicateCall))
	}
}
